/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
    const group = useRef()
    useFrame(({ clock }) => {
        const a = clock.getElapsedTime()
        group.current.rotation.y = a / 3
    })
    const { nodes, materials } = useGLTF('/REVOLVER.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
            <group position={[-15, 7, 0]} rotation={[0, 0, 0]} scale={0.5}>
                <group position={[34.5, -31.42, 0]} rotation={[0, 0, 0]}>
                    <group position={[2.86, 17.57, 0]}>
                        <mesh
                            geometry={nodes.BARILLET_AXE_2.geometry}
                            material={nodes.BARILLET_AXE_2.material}
                            position={[5.03, 0, 0]}
                        />
                    </group>
                    <group position={[20.79, 23.21, 0]}>
                        <group position={[-12.91, -5.64, 0]}>
                            <mesh
                                geometry={nodes.BARILLET_2.geometry}
                                material={nodes.BARILLET_2.material}
                            />
                        </group>
                        <mesh
                            geometry={nodes.AXES_1.geometry}
                            material={nodes.AXES_1.material}
                            position={[-12.91, -5.64, 0]}
                        />
                        <mesh
                            geometry={nodes.DETAIL_1.geometry}
                            material={nodes.DETAIL_1.material}
                            position={[-12.91, -5.64, 0]}
                        />
                    </group>
                </group>
                <group position={[42.39, -13.85, 0]}>
                    <group position={[0, 0, 2.36]}>
                        <mesh
                            geometry={nodes.BOIS_1.geometry}
                            material={nodes.BOIS_1.material}
                            position={[0, 0, -2.36]}
                        />
                    </group>
                    <mesh
                        geometry={nodes.VIS.geometry}
                        material={nodes.VIS.material}
                        position={[0, 0, 1.86]}
                    />
                </group>
                <group position={[42.39, -13.85, 0]}>
                    <mesh
                        geometry={nodes.BASE_2.geometry}
                        material={nodes.BASE_2.material}
                    />
                    <mesh
                        geometry={nodes.VIS_1.geometry}
                        material={nodes.VIS_1.material}
                        position={[27.42, 6.07, 0]}
                        rotation={[-Math.PI / 2, Math.PI / 9, 0]}
                    />
                    <mesh
                        geometry={nodes.VIS_2.geometry}
                        material={nodes.VIS_2.material}
                        position={[16.98, -15.15, 0]}
                        rotation={[-Math.PI / 2, Math.PI / 9, 0]}
                    />
                    <mesh
                        geometry={nodes.CANON.geometry}
                        material={nodes.CANON.material}
                    />
                    <mesh
                        geometry={nodes.DETAIL.geometry}
                        material={nodes.DETAIL.material}
                    />
                </group>
                <group position={[62.84, -1.9, 0]}>
                    <group position={[-20.45, -11.96, 0]}>
                        <mesh
                            geometry={nodes.CHIEN_2.geometry}
                            material={nodes.CHIEN_2.material}
                        />
                    </group>
                    <mesh
                        geometry={nodes.AXES.geometry}
                        material={nodes.AXES.material}
                        position={[-20.45, -11.96, 0]}
                    />
                    <mesh
                        geometry={nodes.CHIENDETAIL.geometry}
                        material={nodes.CHIENDETAIL.material}
                        position={[-20.45, -11.96, 0]}
                    />
                </group>
                <group position={[62.87, -31.33, 0]}>
                    <group position={[-20.49, 17.48, 0]}>
                        <mesh
                            geometry={nodes.GACHETTE_2.geometry}
                            material={nodes.GACHETTE_2.material}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/REVOLVER.gltf')
